language: java
jdk:
- oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: ljD0+vOUm6skWfYbOpSIdP3xNL70aYTy3S65Te5ggUiy8cz0PTLUGFlfJuUch7ppLvEAwFDyIQw+BEWeapAZFg7Spl9vdTra53VhjbW26V9GiNO8u75/Jfy9OUHasdB5UpSp4p3IznFAN/cBnge2xdKZ+iOA1vl1gIl7OdHIkM8rJ4alBIYKlRL2m3mPtGzw9swj2NnLoiwCcgQUvbSKSN7KBVgLYrgpgTW17DXNgsCpu5woV3YZP6Dr9/e3OEkhoYQjQigB1HFT7cnmlK0bqjxv/6pUYFhL2LXysilGx67VbN3onQnTszDgXwSQSAKWGSu9wkpNkj2Z3Pl1a9eUsplo/ndsESxNbr+K59KmWtERtkpmiiA7NiXklCbeg3Dsa+t+EOfAyygD8e+C9KvcpqPtGt+tWKn9NkPHG9GjiCmHAaGOfEGlh/15p41n0pVxL+wB7n49t7cIlFYCe1Qd3T46tFavXax8FSDIBJENhe7wo72VUtiKYwVgNu7qkDcOu3zGKOiKlqQEfUa9+nQKVHvWgu2MnZf4oEF+H+yc/uG/pIFnXBHwYcaHbZY2l4gDZytQHwK4LB0KV4ZZml8XK2QOVgEa024cvYX56xKhD7bt59NCYrVj4OtpGzmVVojPkXLYKUU/Jpw9ldgeBVJ11ifJaHwS0PaxwLbmhweZLew=
  file: target/Werewolf-*.jar
  skip_cleanup: true
  on:
    repo: DoggyCraftDK/Werewolf
    tags: true
sudo: false
